#! /bin/sh
### BEGIN INIT INFO
# Provides: ckrun
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-description: Color Kinetics daemon
# Description: Start and stop the ckrun script.
### END INIT INFO

RETVAL=0


start() {
echo -n ""Starting dandrun ckrun: ""
pgrep -f dandrun
RETVAL=$?
[ $RETVAL -eq 0 ] && echo ""dandrun already running: Exiting"" && exit 1

# this call actually starts dandrun ckrun.
/home/jsalem/ck/bin/dandrun > /dev/null 2>&1 &
RETVAL=$?
[ $RETVAL -eq 0 ] && echo -n ""done""
echo
return $RETVAL
}

stop() {
echo -n ""Stopping dandrun ckrun: ""
pkill -f dandrun
RETVAL=$?
echo
[ $RETVAL -eq 0 ] && echo -n ""done""
echo
return $RETVAL
}

# See how we were called.
case ""$1"" in
start)
start
;;
stop)
stop
;;
restart|reload)
stop
sleep 1
start
RETVAL=$?
;;
*)
echo ""Usage: $0 {start|stop|restart}""
exit 1
esac
exit $RETVAL
